services:
  npm:
    build:
      dockerfile: Docker/npm.Dockerfile
    ports:
      - 8000:5174
    volumes:
      - './Client:/var/www/html'
    environment:
      - HOST=0.0.0.0
      - PORT=5174
    depends_on:
      - pg

  pg:
    image: postgres:latest
    # platform: linux/x86_64
    ports:
      - "8001:5432"
    volumes:
      - qrbuddy-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_DB: 'qrbuddy'
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '8003:1025'
      - '8004:8025'

volumes:
  qrbuddy-pg:
    driver: local
